"""initial

Revision ID: 15f4d7f67585
Revises: 
Create Date: 2026-03-07 16:06:14.605513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '15f4d7f67585'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('free_games', schema=None) as batch_op:
        batch_op.alter_column('expiry_datetime',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('game_user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('played_before', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enjoyment_score', sa.Float(), nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('owned')
        batch_op.drop_column('enjoyment_scores')
        batch_op.drop_column('played_before')
        batch_op.drop_column('votes')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('played_before', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('enjoyment_scores', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('owned', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('game_user_data', schema=None) as batch_op:
        batch_op.drop_column('enjoyment_score')
        batch_op.drop_column('played_before')
        batch_op.drop_column('owned')

    with op.batch_alter_table('free_games', schema=None) as batch_op:
        batch_op.alter_column('expiry_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
