"""initial migration

Revision ID: a7d2d922facc
Revises: 
Create Date: 2026-03-07 16:41:15.380489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d2d922facc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_games',
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('shop_name', sa.String(), nullable=False),
    sa.Column('expiry_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('GAME', 'DLC', 'PACKAGE', name='gametype'), nullable=False),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('global_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bedtimes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('bedtime_time', sa.Time(), nullable=False),
    sa.Column('scheduler_job_id', sa.String(), nullable=True),
    sa.Column('scheduler_job_late_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'server_id')
    )
    op.create_table('free_game_subscribers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('games',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('submitter', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.Column('steam_id', sa.Integer(), nullable=True),
    sa.Column('price_current', sa.Float(), nullable=True),
    sa.Column('price_original', sa.Float(), nullable=True),
    sa.Column('local', sa.Boolean(), nullable=True),
    sa.Column('release_state', sa.Enum('RELEASED', 'EARLY_ACCESS', 'UNRELEASED', name='releasestate'), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('finished_timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('server_id', 'id')
    )
    op.create_table('live_messages',
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('message_type', sa.Enum('LIST', 'HALL_OF_GAME', name='livemessagetype'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('live_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_messages_server_id'), ['server_id'], unique=False)

    op.create_table('server_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'server_id')
    )
    op.create_table('game_user_data',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Float(), nullable=True),
    sa.Column('owned', sa.Boolean(), nullable=True),
    sa.Column('played_before', sa.Boolean(), nullable=True),
    sa.Column('enjoyment_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('server_id', 'game_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_user_data')
    op.drop_table('server_members')
    with op.batch_alter_table('live_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_messages_server_id'))
        batch_op.drop_index(batch_op.f('ix_live_messages_message_type'))

    op.drop_table('live_messages')
    op.drop_table('games')
    op.drop_table('free_game_subscribers')
    op.drop_table('bedtimes')
    op.drop_table('users')
    op.drop_table('servers')
    op.drop_table('free_games')
    # ### end Alembic commands ###
