"""renamed tags to notes in games

Revision ID: 0a8f6e614561
Revises: 7f9ad5f93626
Create Date: 2026-03-21 17:08:43.644872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0a8f6e614561'
down_revision: Union[str, Sequence[str], None] = '7f9ad5f93626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.JSON(), nullable=True))
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sqlite.JSON(), nullable=True))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
