"""support free games without timestamps

Revision ID: 1da9228e63a4
Revises: 669029321cab
Create Date: 2026-04-23 20:13:44.430885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da9228e63a4'
down_revision: Union[str, Sequence[str], None] = '669029321cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('free_games', schema=None) as batch_op:
        batch_op.alter_column('expiry_datetime',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('free_games', schema=None) as batch_op:
        batch_op.alter_column('expiry_datetime',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
