"""added selected users to live message

Revision ID: 669029321cab
Revises: 0a8f6e614561
Create Date: 2026-04-05 16:38:28.446311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '669029321cab'
down_revision: Union[str, Sequence[str], None] = '0a8f6e614561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_user_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_messages', schema=None) as batch_op:
        batch_op.drop_column('selected_user_ids')

    # ### end Alembic commands ###
