"""added steam_id column to server_members

Revision ID: 7f9ad5f93626
Revises: a7d2d922facc
Create Date: 2026-03-21 15:29:37.038225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9ad5f93626'
down_revision: Union[str, Sequence[str], None] = 'a7d2d922facc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_members', schema=None) as batch_op:
        batch_op.drop_column('steam_id')

    # ### end Alembic commands ###
